#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [[ -z ${ORG} ]] || [[ -z ${REPO} ]] || [[ -z ${TAG} ]]; then
    echo "Usage: [REGISTRY=] ORG= REPO= TAG= ./scripts/package"
    exit 1
fi

IMAGE=${ORG}/${REPO}:${TAG}
if [[ -n ${REGISTRY} ]]; then
    IMAGE=${REGISTRY%/}/${IMAGE}
fi
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

# Build for ARM64 (default)
docker build -f ${DOCKERFILE} -t ${IMAGE}-arm64 .

# Build for ARM64
docker build --platform=linux/arm64 -f ${DOCKERFILE} -t ${IMAGE}-arm64 .

# Build for AMD64
docker build --platform=linux/amd64  -f ${DOCKERFILE} -t ${IMAGE}-amd64 .
echo Built ${IMAGE}
